import React, { useState, useRef, useEffect } from 'react';
import { 
  Bot, 
  Send, 
  Sparkles, 
  Plus, 
  Trash2, 
  ChevronRight, 
  Flame, 
  User, 
  Layers,
  HelpCircle,
  Brain,
  Terminal,
  Clock,
  ShieldCheck,
  CheckCircle2
} from 'lucide-react';
import { ChatMessage, Task, Priority } from '../types';

interface AIAssistantPageProps {
  messages: ChatMessage[];
  darkMode: boolean;
  onSendMessage: (text: string) => Promise<any>;
  onAddTask: (task: Omit<Task, 'id' | 'createdAt'>) => void;
  loading: boolean;
}

export default function AIAssistantPage({
  messages,
  darkMode,
  onSendMessage,
  onAddTask,
  loading,
}: AIAssistantPageProps) {
  const [inputText, setInputText] = useState('');
  const [detectedTask, setDetectedTask] = useState<any>(null);
  
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Suggested prompt chips
  const promptSuggestions = [
    { text: "Add a task: Review biology report by tomorrow 5pm as High priority", label: "📋 Add Task" },
    { text: "Give me an aggressive motivational nudge to finish writing", label: "🔥 Get Nudge" },
    { text: "How can I structure focus blocks to study for 3 hours?", label: "⏱️ Focus Structure" },
    { text: "Analyze my tasks and tell me where I am procrastinating", label: "🧠 Procrastination Audit" },
  ];

  // Auto-scroll to bottom of chat
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim() || loading) return;

    const textToSend = inputText;
    setInputText('');
    setDetectedTask(null);

    const result = await onSendMessage(textToSend);
    if (result && result.suggestedTask) {
      setDetectedTask(result.suggestedTask);
    }
  };

  const handleSuggestionClick = async (text: string) => {
    if (loading) return;
    setInputText('');
    setDetectedTask(null);
    const result = await onSendMessage(text);
    if (result && result.suggestedTask) {
      setDetectedTask(result.suggestedTask);
    }
  };

  const handleAddDetectedTask = () => {
    if (!detectedTask) return;
    onAddTask({
      title: detectedTask.title,
      description: detectedTask.description || 'Auto-generated by AI Assistant',
      priority: (detectedTask.priority || 'High') as Priority,
      status: 'ToDo',
      dueDate: detectedTask.dueDate || new Date().toISOString().split('T')[0],
      timeEstimated: Number(detectedTask.timeEstimated || 60),
      category: detectedTask.category || 'Academic',
      subtasks: [],
    });
    setDetectedTask(null);
    alert(`Task "${detectedTask.title}" added to your board successfully!`);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-[calc(100vh-140px)]">
      
      {/* Left Chat Pane: Dialog Feed */}
      <div className={`lg:col-span-8 p-5 rounded-2xl border flex flex-col justify-between shadow-sm h-full ${
        darkMode 
          ? 'bg-slate-900/35 border-slate-800/80' 
          : 'bg-white border-slate-200'
      }`}>
        
        {/* Chat Feed Header */}
        <div className="flex items-center justify-between border-b border-slate-700/10 pb-3 mb-4 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-purple-500/10 text-purple-400 border border-purple-500/10">
              <Bot className="w-5 h-5" />
            </div>
            <div>
              <h4 className="font-sans font-bold text-sm tracking-tight">Rescue Coach Dialog Terminal</h4>
              <span className="text-[10px] font-mono opacity-50 block">AI Gemini-3.5 Agent Online</span>
            </div>
          </div>
          <div className="flex items-center gap-1">
            <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-[10px] font-mono opacity-60">Connected</span>
          </div>
        </div>

        {/* Message Bubble Feed Container */}
        <div className="flex-1 overflow-y-auto space-y-4 mb-4 pr-1.5 scrollbar-thin">
          {messages.length === 0 ? (
            <div className="py-20 flex flex-col items-center justify-center text-center space-y-3.5 max-w-sm mx-auto">
              <div className="p-4 rounded-full bg-indigo-500/10 border border-indigo-500/15">
                <Sparkles className="w-8 h-8 text-indigo-400 animate-pulse" />
              </div>
              <h5 className="text-sm font-sans font-bold tracking-tight">Initiate Accountability Protocol</h5>
              <p className="text-xs opacity-65 leading-relaxed font-sans">
                I am your high-intensity productivity partner. You can prompt me to create tactical tasks, plan study sprints, audit procrastination triggers, or draft emergency schedule blocks.
              </p>
            </div>
          ) : (
            messages.map((msg) => {
              const isAssistant = msg.sender === 'assistant';
              return (
                <div
                  key={msg.id}
                  className={`flex gap-3 max-w-[85%] ${
                    isAssistant ? 'self-start mr-auto' : 'self-end ml-auto flex-row-reverse'
                  }`}
                >
                  {/* Sender Avatar */}
                  <div className={`h-8 w-8 rounded-full border flex items-center justify-center shrink-0 text-xs font-mono font-bold ${
                    isAssistant
                      ? 'bg-purple-500/10 text-purple-400 border-purple-500/15'
                      : 'bg-indigo-600/10 text-indigo-400 border-indigo-500/15'
                  }`}>
                    {isAssistant ? 'AI' : 'U'}
                  </div>

                  {/* Message Bubble Box */}
                  <div className={`p-4 rounded-2xl text-xs font-sans leading-relaxed border ${
                    isAssistant
                      ? darkMode
                        ? 'bg-slate-950/40 border-slate-800 text-slate-300'
                        : 'bg-slate-50 border-slate-100 text-slate-800'
                      : 'bg-indigo-600 border-indigo-500 text-white'
                  }`}>
                    {msg.text}
                  </div>
                </div>
              );
            })
          )}

          {/* Typing Indicator */}
          {loading && (
            <div className="flex gap-3 self-start mr-auto max-w-[80%] animate-pulse">
              <div className="h-8 w-8 rounded-full bg-purple-500/10 border border-purple-500/15 flex items-center justify-center text-xs text-purple-400 font-mono">
                AI
              </div>
              <div className={`p-4 rounded-2xl text-xs border flex items-center gap-1.5 ${
                darkMode ? 'bg-slate-950/40 border-slate-800 text-slate-400' : 'bg-slate-50 border-slate-100 text-slate-600'
              }`}>
                <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-bounce"></span>
                <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-bounce delay-100"></span>
                <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-bounce delay-200"></span>
                <span className="font-mono text-[10px] opacity-70 ml-1">Gemini is strategizing...</span>
              </div>
            </div>
          )}

          <div ref={chatEndRef} />
        </div>

        {/* Suggested Chips Under Message Box (Shrinks or hides when loading) */}
        {!loading && (
          <div className="flex items-center gap-2 overflow-x-auto pb-3 select-none">
            {promptSuggestions.map((suggestion, index) => (
              <button
                key={index}
                onClick={() => handleSuggestionClick(suggestion.text)}
                className={`px-3 py-1.5 rounded-full text-[10px] font-sans font-semibold border whitespace-nowrap transition-all hover:bg-indigo-500/10 hover:border-indigo-500/25 shrink-0 cursor-pointer ${
                  darkMode ? 'bg-slate-950/40 border-slate-800 text-slate-300' : 'bg-slate-50 border-slate-200 text-slate-700'
                }`}
              >
                {suggestion.label}
              </button>
            ))}
          </div>
        )}

        {/* Text Input Box */}
        <form onSubmit={handleSubmit} className="flex gap-2.5 shrink-0 border-t border-slate-700/10 pt-3">
          <input
            type="text"
            value={inputText}
            disabled={loading}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Type your study goal or tactical task request..."
            className={`flex-1 px-4 py-3 rounded-xl border text-xs focus:ring-1 focus:ring-indigo-500 focus:outline-none ${
              darkMode ? 'bg-slate-950 border-slate-800 text-slate-100' : 'bg-slate-50 border-slate-200'
            }`}
          />
          <button
            type="submit"
            disabled={!inputText.trim() || loading}
            className={`p-3 rounded-xl flex items-center justify-center transition-all cursor-pointer ${
              inputText.trim() && !loading
                ? 'bg-indigo-600 text-white hover:bg-indigo-700 shadow-md shadow-indigo-500/10'
                : 'bg-slate-800 border border-slate-700 text-slate-500 cursor-not-allowed'
            }`}
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
      </div>

      {/* Right Pane: AI Task Extraction Overlay Panel */}
      <div className={`lg:col-span-4 p-5 rounded-2xl border flex flex-col justify-between shadow-sm h-full ${
        darkMode 
          ? 'bg-slate-900/35 border-slate-800/80' 
          : 'bg-white border-slate-200'
      }`}>
        <div className="space-y-4">
          <div className="flex items-center gap-2 border-b border-slate-700/10 pb-3">
            <div className="p-1.5 rounded-lg bg-indigo-500/10 text-indigo-400">
              <Terminal className="w-4 h-4" />
            </div>
            <h4 className="font-sans font-bold text-sm tracking-tight">Extraction Pipeline</h4>
          </div>

          {detectedTask ? (
            <div className={`p-4 rounded-xl border relative overflow-hidden space-y-3.5 animate-bounce ${
              darkMode ? 'bg-indigo-950/25 border-indigo-900/50' : 'bg-indigo-50 border-indigo-100'
            }`}>
              <div className="flex items-center gap-1.5 text-xs text-indigo-400 font-bold font-mono">
                <Sparkles className="w-4 h-4 animate-pulse" />
                <span>AI EXTRACTED ACTION ITEM</span>
              </div>

              <div className="space-y-1.5 text-xs">
                <span className="text-[10px] font-mono opacity-50 block uppercase tracking-wider">
                  📂 {detectedTask.category || 'General'}
                </span>
                <h5 className="font-sans font-bold text-sm tracking-tight">
                  {detectedTask.title}
                </h5>
                <p className="opacity-75 font-sans leading-relaxed text-xs">
                  {detectedTask.description || 'Auto-parsed from discussion details.'}
                </p>
                <div className="flex items-center gap-3 pt-1 text-[11px] font-mono opacity-65">
                  <span>⏱️ {detectedTask.timeEstimated || 60} mins</span>
                  <span>📅 Due: {detectedTask.dueDate}</span>
                  <span className="bg-indigo-500/20 px-1.5 py-0.5 rounded text-[9px] font-bold text-indigo-400">
                    {detectedTask.priority}
                  </span>
                </div>
              </div>

              <button
                type="button"
                onClick={handleAddDetectedTask}
                className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs font-sans transition-all shadow-md shadow-indigo-500/10"
              >
                <Plus className="w-4 h-4" /> Approve & Add to Matrix
              </button>
            </div>
          ) : (
            <div className="py-16 text-center opacity-45 border-2 border-dashed border-slate-700/10 rounded-xl space-y-2">
              <Bot className="w-10 h-10 mx-auto opacity-50" />
              <p className="text-xs font-sans max-w-xs mx-auto">
                No new tactical targets extracted. Ask me to "Add a task to..." to watch me parse details and display them here.
              </p>
            </div>
          )}
        </div>

        {/* Coach tip box */}
        <div className="p-3.5 rounded-xl bg-gradient-to-tr from-purple-500/10 to-indigo-500/10 border border-indigo-500/20 text-xs font-sans flex items-start gap-2">
          <Brain className="w-4 h-4 text-purple-400 shrink-0 mt-0.5" />
          <div className="space-y-1 text-xs">
            <h6 className="font-bold">Prompt Mastery Tip:</h6>
            <p className="leading-relaxed opacity-85">
              Type naturally: "I have a chemistry exam next Tuesday that takes 90 mins" and watch the AI coordinate, estimate, and deploy it onto your Board instantly.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
